apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: ft_services
spec:
    ports:
    - port: 3306
    selector:
        app: ft_services
        tier: mysql
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
    labels:
        app: ft_services
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    labels:
        app: ft_services
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ft_services
            tier: mysql
        strategy:
            type: Recreate
        template:
            metadata:
                labels:
                    app: ft_services
                    tier: mysql
            spec:
                restartPolicy: Always
                containers:
                - name: mysql
                  image: mysql_alpine
                  imagePullPolicy: Never
                  env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: password
                  - name: MYSQL_DATABASE
                    value: wordpress
                  - name: MYSQL_USER
                    value: root
                  - name: MYSQL_PASSWORD
                    value: password
                  ports:
                  - containerPort: 3306
                    name: mysql
                  volumeMounts:
                  - name: mysql-persistent-storage
                    mountPath: /app/mysql
                volumes:
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                      claimName: mysql-pv-claim
