apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        app: ft_services
spec:
    ports:
        - port: 80
          targetPort: 80
          name: http
          protocol: TCP
        - port: 443
          targetPort: 443
          name: https
          protocol: TCP
        - port: 22
          targetPort: 22
          name: ssh
    selector:
        app: ft_services
        tier: nginx
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: ft_services
spec:
    replicas: 3
    selector:
        matchLabels:
            app: ft_services
            tier: nginx
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: ft_services
                tier: nginx
        spec:
            restartPolicy: Always
            containers:
            - name: nginx
              image: nginx_alpine
              imagePullPolicy: Never
              ports:
              - containerPort: 80
                name: http
              - containerPort: 443
                name: https
              - containerPort: 22
                name: ssh
