apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 172.17.0.12
  ports:
    - port: 5050
      targetPort: 5050
      name: wordpress
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - pidof telegraf
        #     initialDelaySeconds: 30
        #     periodSeconds: 2
